name = "centos-base"
description = "CentOS Base Image"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "podman"
version = "*"

[[packages]]
name = "osbuild"
version = "*"

[[packages]]
name = "tmux"
version = "*"
