name = "centos-base"
description = "CentOS Base Image"
version = "0.0.2"
modules = []
groups = []

[[packages]]
name = "cockpit-composer"
version = "*"

[[packages]]
name = "osbuild"
version = "*"

[[packages]]
name = "osbuild-composer"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[customizations.services]
enabled = ["cockpit.socket", "osbuild-composer.socket"]
