name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    # services:
    #   imagebuilder:
    #     image: quay.io/major/centos-imagebuilder
    #     options: >-
    #       --name=imagebuilder
    #       --privileged
    #     volumes:
    #       - /tmp/imagebuilder:/imagebuilder
    steps:
      - uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Image Builder container
        uses: docker/build-push-action@v2.4.0
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: .
          file: Dockerfile
          load: true
          push: false
          tags: imagebuilder:latest

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Start the Image Builder container
        run: docker run --detach --rm --privileged -v $(pwd):/repo:ro --name imagebuilder imagebuilder
          
      - name: Verify Image Builder is running
        run: docker exec -t imagebuilder composer-cli status show

