name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    # services:
    #   imagebuilder:
    #     image: quay.io/major/centos-imagebuilder
    #     options: >-
    #       --name=imagebuilder
    #       --privileged
    #     volumes:
    #       - /tmp/imagebuilder:/imagebuilder
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build only
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: Dockerfile
          push: false
          tags: centos-imagebuilder

      - name: Verify that Image Builder is running
        run: |
          docker ps --all
          docker run --rm --privileged -v $(pwd):/repo:ro --name imagebuilder centos-imagebuilder
          docker ps --all
          docker exec imagebuilder composer-cli status show
