name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      imagebuilder:
        image: quay.io/major/centos-imagebuilder
        options: >-
          --name=imagebuilder
          --privileged
        volumes:
          - /tmp/imagebuilder:/imagebuilder
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Verify that Image Builder is running
        run: |
          docker ps --all
          docker run --rm --privileged -v $(pwd):/repo:ro --name imagebuilder-manual quay.io/major/centos-imagebuilder
          #echo ${{ job.services.imagebuilder }}
          #docker exec imagebuilder composer-cli status show
